//! monocle-proto — Protobuf wire-format crate for monocle hook events.
//!
//! Populated by S-013 with canonical 4-field envelope
//! (`schema_version=1`, `session_id=2`, `timestamp_micros=3`, `pid=4`) + `oneof event`
//! carrying 5 inner messages (`SessionStartEvent`, `UserPromptSubmitEvent`,
//! `PreToolUseEvent`, `NotificationEvent`, `StopEvent`).
//!
//! # Phase boundary
//!
//! Phase 1: prost-build generates Rust types from the proto schema at compile time.
//! No wire path is activated at runtime — the types are compiled into the binary and
//! available for Phase 4 without any Phase 4 workspace changes to `monocle-proto`.
//!
//! Phase 4: activates the wire path for cross-host federation. The `monocle-ipc` crate
//! (Phase 4 deliverable) will deserialize `HookEnvelope` messages from untrusted network
//! input.
//!
//! # Field number contract (FC-05 immutability)
//!
//! Field numbers 1–99 are immutable across Phase 1 minor versions. Any change to
//! these field numbers is a BREAKING change requiring a `schema_version` bump and an ADR.
//! See `SS-forward-compatibility.md v1.2.19 §FC-05` for the full immutability contract.
//!
//! # E-PROTO-001 — Phase 4 schema_version dispatch rule
//!
//! When Phase 4 federation nodes receive a `HookEnvelope`, they MUST check
//! `schema_version` BEFORE deserializing the `oneof event` payload.
//! Any `schema_version` value that is not recognized (i.e., != 1 for Phase 1
//! consumers) MUST result in:
//!
//! ```text
//! WARN: HookEnvelope schema_version <N> not recognized; skipping
//! ```
//!
//! The message is skipped without panic and without propagating an error to
//! the caller. This is the E-PROTO-001 not recognized skip behavior.
//!
//! - Value 0 is explicitly invalid (not a defined version).
//! - Value 1 is the Phase 1 canonical value; always accepted.
//! - Values >= 2 are reserved for future schema versions; skip with WARN.
//!
//! Phase 1 invariant: no Phase 1 code path sets schema_version to any value
//! other than 1. The AC-005 negative oracle (grep test) asserts this.

#![deny(missing_docs)]
#![forbid(unsafe_code)]

/// Generated protobuf types for the `monocle.v1` package.
pub mod monocle {
    /// Version 1 of the monocle wire protocol.
    ///
    /// All types in this module are generated by prost-build from
    /// `proto/monocle/v1/hook_envelope.proto`. The generated code does not carry
    /// rustdoc comments; see the crate-level documentation for the E-PROTO-001
    /// dispatch contract and FC-05 field number immutability invariant.
    #[allow(missing_docs)]
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/monocle.v1.rs"));
    }
}

/// Re-export of the top-level generated types for ergonomic access.
///
/// Consumers can use `monocle_proto::HookEnvelope` directly without navigating
/// the full `monocle::v1` path.
pub use monocle::v1::*;
