//! monocle-session-host — per-session supervisor process (S-033).
//!
//! This binary is spawned by the monocle daemon's `RealSessionHostSpawner` for each
//! new session. It owns the PTY master, vt100 parser, harness child handle, and
//! per-session UDS socket.
//!
//! # Startup sequence (SS-session-manager.md §monocle-session-host binary §startup sequence)
//!
//! 1. Parse CLI args: --session-id, --runtime-dir, --binary, --args, --env, --cwd
//! 2. Call nix::unistd::setsid() to become a process group leader
//! 3. Open PTY pair via portable_pty::openpty(PtySize { rows: 24, cols: 80, ... })
//! 4. Build CommandBuilder from --binary/--args/--env/--cwd with env inheritance
//! 5. Spawn harness child on PTY slave
//! 6. Initialize vt100::Parser with initial size
//! 7. Bind per-session UDS socket at <runtime_dir>/session-<session_id>.sock (mode 0o600)
//! 8. Write session-state.json sidecar at <runtime_dir>/session-<session_id>.json
//! 9. Enter main event loop
//!
//! # Error handling
//! All errors at startup cause process exit with a non-zero code. The daemon's
//! post-spawn monitor handles session-host death by transitioning to Terminated.

#![forbid(unsafe_code)]
#![deny(missing_docs)]

/// Maximum length-prefix frame size for per-session UDS messages (DaemonToHost / HostToDaemon).
/// Spec: SS-session-manager.md §Per-session UDS protocol — "4-byte LE u32 + JSON payload, 256 KiB max".
/// MED-002 fix: was 1 MiB; corrected to 256 KiB per spec bound.
const MAX_FRAME_LEN: usize = 256 * 1024;

use std::collections::HashMap;
use std::path::PathBuf;

use tokio::io::AsyncWriteExt;

/// CLI arguments parsed from the daemon-supplied command line.
///
/// Passed by `RealSessionHostSpawner::spawn()` per SS-session-manager.md
/// §SessionHostSpawner trait.
#[derive(Debug)]
#[allow(dead_code)]
struct CliArgs {
    /// Session UUID string (pre-generated by daemon IPC handler).
    session_id: String,
    /// Daemon's runtime directory (for sidecar + UDS socket placement).
    runtime_dir: PathBuf,
    /// Absolute path to the harness binary (from SpawnRecipe.binary).
    binary: PathBuf,
    /// Harness CLI arguments (from SpawnRecipe.args), JSON-encoded.
    args: Vec<String>,
    /// Env overlay (from SpawnRecipe.env), JSON-encoded key=value pairs.
    env: HashMap<String, String>,
    /// Working directory for the harness child (from SpawnRecipe.cwd).
    cwd: PathBuf,
}

/// Parse CLI arguments from `std::env::args()`.
///
/// Parses: `--session-id <id> --runtime-dir <path> --binary <path>
///   --args <json> --env <json> --cwd <path>`
fn parse_args() -> Result<CliArgs, String> {
    let mut args = std::env::args().skip(1);
    let mut session_id = None::<String>;
    let mut runtime_dir = None::<PathBuf>;
    let mut binary = None::<PathBuf>;
    let mut args_json = None::<String>;
    let mut env_json = None::<String>;
    let mut cwd = None::<PathBuf>;

    while let Some(flag) = args.next() {
        match flag.as_str() {
            "--session-id" => {
                session_id = Some(args.next().ok_or("--session-id requires a value")?);
            }
            "--runtime-dir" => {
                runtime_dir = Some(PathBuf::from(
                    args.next().ok_or("--runtime-dir requires a value")?,
                ));
            }
            "--binary" => {
                binary = Some(PathBuf::from(
                    args.next().ok_or("--binary requires a value")?,
                ));
            }
            "--args" => {
                args_json = Some(args.next().ok_or("--args requires a value")?);
            }
            "--env" => {
                env_json = Some(args.next().ok_or("--env requires a value")?);
            }
            "--cwd" => {
                cwd = Some(PathBuf::from(args.next().ok_or("--cwd requires a value")?));
            }
            other => {
                return Err(format!("unknown flag: {other}"));
            }
        }
    }

    let session_id = session_id.ok_or("missing --session-id")?;
    let runtime_dir = runtime_dir.ok_or("missing --runtime-dir")?;
    let binary = binary.ok_or("missing --binary")?;
    let cwd = cwd.ok_or("missing --cwd")?;

    let harness_args: Vec<String> = args_json
        .as_deref()
        .map(|j| serde_json::from_str(j).map_err(|e| format!("--args JSON parse error: {e}")))
        .transpose()?
        .unwrap_or_default();

    let env: HashMap<String, String> = env_json
        .as_deref()
        .map(|j| serde_json::from_str(j).map_err(|e| format!("--env JSON parse error: {e}")))
        .transpose()?
        .unwrap_or_default();

    Ok(CliArgs {
        session_id,
        runtime_dir,
        binary,
        args: harness_args,
        env,
        cwd,
    })
}

/// Session-host error types.
#[derive(Debug, thiserror::Error)]
#[allow(dead_code)]
enum SessionHostError {
    /// PTY open failed.
    #[error("PTY open failed: {0}")]
    PtyOpenFailed(String),

    /// Harness child spawn failed.
    #[error("harness child spawn failed: {0}")]
    ChildSpawnFailed(String),

    /// UDS socket bind failed.
    #[error("UDS bind failed: {path}: {reason}")]
    UdsBindFailed {
        /// Path of the UDS socket.
        path: String,
        /// Reason for the bind failure.
        reason: String,
    },

    /// Sidecar write failed.
    #[error("sidecar write failed: {path}: {reason}")]
    SidecarWriteFailed {
        /// Path of the sidecar file.
        path: String,
        /// Reason for the write failure.
        reason: String,
    },

    /// I/O error.
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// Argument parse error.
    #[error("argument error: {0}")]
    ArgError(String),
}

/// Entry point. Parses CLI args, runs the startup sequence, enters the event loop.
#[tokio::main]
async fn main() {
    // Initialize tracing subscriber for structured session-host logs.
    // Errors are not surfaced to the daemon via stderr alone (I3-009 — degraded env
    // is surfaced via HostToDaemon::StateChanged { degraded_env: Some(_) }).
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive(tracing::Level::INFO.into()),
        )
        .with_writer(std::io::stderr)
        .init();

    let args = match parse_args() {
        Ok(a) => a,
        Err(e) => {
            tracing::error!("monocle-session-host arg parse error: {e}");
            std::process::exit(1);
        }
    };

    if let Err(e) = run(args).await {
        tracing::error!("monocle-session-host fatal error: {e}");
        std::process::exit(1);
    }
}

/// Run the session-host startup sequence and event loop.
async fn run(args: CliArgs) -> Result<(), SessionHostError> {
    // Step 2: become a process group leader (immune to SIGHUP from daemon exit).
    step_setsid()?;

    // Step 3: open PTY pair (24×80 initial size).
    let pty_system = portable_pty::native_pty_system();
    let pty_pair = pty_system
        .openpty(portable_pty::PtySize {
            rows: 24,
            cols: 80,
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|e| SessionHostError::PtyOpenFailed(e.to_string()))?;

    // Step 4: build CommandBuilder with env inheritance + recipe overlay.
    let cmd = step_build_command(&args)?;

    // Step 5: spawn harness child on PTY slave.
    let mut child = pty_pair
        .slave
        .spawn_command(cmd)
        .map_err(|e| SessionHostError::ChildSpawnFailed(e.to_string()))?;
    let child_pid = child.process_id().ok_or_else(|| {
        SessionHostError::ChildSpawnFailed("child PID unavailable after spawn".to_string())
    })?;

    // Step 6: initialize vt100 parser (BC-2.09.006: resized in DaemonToHost::Resize handler).
    let mut _parser = step_init_vt100_parser(24, 80);

    // Step 7: bind per-session UDS socket with mode 0o600.
    let listener = step_bind_uds(&args.runtime_dir, &args.session_id).await?;

    // Step 8: write session-state.json sidecar atomically with child_pid.
    step_write_sidecar(&args, child_pid).await?;

    // Step 9: enter main event loop (pass pty_master and parser for DaemonToHost::Resize handling).
    let socket_path = args
        .runtime_dir
        .join(format!("session-{}.sock", args.session_id));
    step_event_loop(
        &args.session_id,
        listener,
        child_pid,
        socket_path,
        pty_pair.master,
        &mut _parser,
    )
    .await?;

    // Reap child process to avoid zombie.
    let _ = child.wait();

    Ok(())
}

/// Step 2: Become a process group leader (immune to SIGHUP from daemon exit).
fn step_setsid() -> Result<(), SessionHostError> {
    nix::unistd::setsid()
        .map(|_| ())
        .map_err(|e| SessionHostError::Io(std::io::Error::other(e.to_string())))
}

/// Step 4: Build CommandBuilder with env inheritance + recipe overlay.
///
/// Env inheritance (I2-006 mandatory): seed CommandBuilder with std::env::vars()
/// first, then overlay SpawnRecipe.env on top. Preserves PATH, HOME, TERM.
fn step_build_command(args: &CliArgs) -> Result<portable_pty::CommandBuilder, SessionHostError> {
    let mut cmd = portable_pty::CommandBuilder::new(&args.binary);

    // Seed with current process environment (inherits PATH, HOME, TERM, etc.).
    for (k, v) in std::env::vars() {
        cmd.env(k, v);
    }

    // Overlay recipe-specific env vars (may override inherited vars).
    for (k, v) in &args.env {
        cmd.env(k, v);
    }

    // Set CLI args.
    cmd.args(args.args.iter());

    // Set working directory.
    cmd.cwd(&args.cwd);

    Ok(cmd)
}

/// Step 6: Initialize vt100 parser with initial PTY dimensions and 1000-line scrollback.
///
/// Scrollback capacity: 1000 lines per SS-session-manager.md §Ruling A.
/// The actual PTY-to-TUI byte relay (PtyBytes streaming) is implemented in S-047;
/// for S-033 the parser is created but not actively used.
fn step_init_vt100_parser(rows: u16, cols: u16) -> vt100::Parser {
    vt100::Parser::new(rows, cols, 1000)
}

/// Step 7: Bind per-session UDS socket at `<runtime_dir>/session-<session_id>.sock`
/// with mode 0o600 (per-session UDS security, SS-session-manager.md §Per-session UDS security).
async fn step_bind_uds(
    runtime_dir: &std::path::Path,
    session_id: &str,
) -> Result<tokio::net::UnixListener, SessionHostError> {
    use std::os::unix::fs::PermissionsExt;

    let sock_path = runtime_dir.join(format!("session-{session_id}.sock"));

    // SEC-005 (CWE-59): unconditional best-effort remove before bind — eliminates the
    // TOCTOU race between exists() check and remove_file() that the prior if-exists pattern
    // had. If the socket does not exist, remove_file returns NotFound which we ignore.
    // If removal fails for a real reason (e.g., permission denied), bind() will surface it.
    let _ = std::fs::remove_file(&sock_path);

    let listener = tokio::net::UnixListener::bind(&sock_path).map_err(|e| {
        SessionHostError::UdsBindFailed {
            path: sock_path.to_string_lossy().into_owned(),
            reason: e.to_string(),
        }
    })?;

    // Set permissions to 0o600 (owner read/write only).
    std::fs::set_permissions(&sock_path, std::fs::Permissions::from_mode(0o600)).map_err(|e| {
        SessionHostError::UdsBindFailed {
            path: sock_path.to_string_lossy().into_owned(),
            reason: format!("failed to set socket permissions: {e}"),
        }
    })?;

    Ok(listener)
}

/// Step 8: Read-modify-write session-state.json sidecar (BLOCKER-002 / Ruling B).
///
/// **Ownership protocol (SS-session-manager.md §Ruling B):**
/// - The DAEMON wrote the initial sidecar with all fields populated and `child_pid: None`.
/// - The SESSION-HOST sets ONLY `child_pid = Some(process_id())` and re-persists atomically.
/// - The session-host MUST NOT overwrite daemon-owned fields: `state`, `project_root`,
///   `cwd`, `harness_id`, `profile_id`, `started_at`, `display_name`, or any other field.
///
/// Implementation:
/// 1. Read the existing `SessionSidecarV3` from disk (written by daemon at spawn).
/// 2. Set `child_pid = Some(child_pid)`.
/// 3. Write back atomically via `tempfile::persist` — no field clobber.
async fn step_write_sidecar(args: &CliArgs, child_pid: u32) -> Result<(), SessionHostError> {
    use std::io::Write as _;

    let sidecar_path = args
        .runtime_dir
        .join(format!("session-{}.json", args.session_id));

    // Step 1: read the daemon-written sidecar from disk.
    let existing_json = std::fs::read_to_string(&sidecar_path).map_err(|e| {
        SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: format!("failed to read daemon-written sidecar: {e}"),
        }
    })?;

    let mut sidecar: monocle_ipc::types::SessionSidecarV3 = serde_json::from_str(&existing_json)
        .map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: format!("failed to deserialize daemon-written sidecar: {e}"),
        })?;

    // Step 2: set ONLY child_pid — do NOT touch any other daemon-owned field.
    sidecar.child_pid = Some(child_pid);

    // Step 3: serialize and persist atomically.
    let sidecar_json =
        serde_json::to_vec_pretty(&sidecar).map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: format!("JSON serialization failed: {e}"),
        })?;

    let dir = sidecar_path
        .parent()
        .ok_or_else(|| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: "sidecar path has no parent directory".to_string(),
        })?;

    let mut tmp = tempfile::Builder::new()
        .prefix(".session-sidecar-host-")
        .suffix(".json.tmp")
        .tempfile_in(dir)
        .map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: e.to_string(),
        })?;

    tmp.write_all(&sidecar_json)
        .map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: e.to_string(),
        })?;

    tmp.persist(&sidecar_path)
        .map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: e.error.to_string(),
        })?;

    tracing::debug!(
        session_id = %args.session_id,
        child_pid = child_pid,
        "session-host: sidecar updated with child_pid (Ruling B read-modify-write)"
    );

    Ok(())
}

/// Send a single `HostToDaemon` message as a length-prefixed JSON frame.
///
/// Frame format: 4-byte LE u32 length + JSON body (per SS-session-manager.md §Per-session UDS protocol).
async fn send_host_msg(
    stream: &mut tokio::net::UnixStream,
    msg: &monocle_ipc::types::HostToDaemon,
) -> Result<(), SessionHostError> {
    let body = serde_json::to_vec(msg)
        .map_err(|e| SessionHostError::Io(std::io::Error::other(e.to_string())))?;
    // SEC-006: pre-send frame size guard — outbound messages must not exceed
    // MAX_FRAME_LEN (256 KiB, matching the daemon-side constant in session_manager/mod.rs).
    if body.len() > MAX_FRAME_LEN {
        return Err(SessionHostError::Io(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!(
                "outbound message exceeds MAX_FRAME_LEN: {} bytes",
                body.len()
            ),
        )));
    }
    let len = body.len() as u32;
    stream.write_all(&len.to_le_bytes()).await?;
    stream.write_all(&body).await?;
    stream.flush().await?;
    Ok(())
}

/// Step 9: Main event loop — S-034 scope: two-phase accept-loop with Kill handler.
///
/// The `UnixListener` is bound ONCE at startup and persists for the session lifetime.
/// The event loop has two structural phases:
///
/// **Phase A — Detached (waiting for daemon connection):**
/// Loops on `listener.accept()`. SO_PEERCRED checked on every accepted connection
/// before any I/O; UID mismatch closes the connection and re-accepts.
/// PTY processing (vt100 parser) is deferred to S-047.
///
/// **Phase B — Active (one daemon connection):**
/// Processes the single active control connection:
/// - `DaemonToHost::Kill` → kill sequence → exit (no re-accept).
/// - `DaemonToHost::Detach` → drop connection → return to Phase A.
/// - EOF (daemon crash/restart) → drop connection → return to Phase A.
/// - `DaemonToHost::Resize { rows, cols }` → calls `apply_resize_to_pty_and_parser()` (BC-2.09.006 PC-6/7, S-042).
/// - Other variants (Attach/KeyInput) → S-035/S-047 scope; logged and ignored.
///
/// **S-034 additions (this story):**
/// - Kill dispatch: SIGTERM to harness child → 10s wait → SIGKILL escalation →
///   sends `HostToDaemon::StateChanged{Terminated}` → sends `HostToDaemon::Goodbye`
///   → removes socket file → exits.
/// - Detach/EOF handling: drop connection, loop back to Phase A (re-accept).
/// - Startup handshake sent once on the FIRST accepted connection (see HIGH-001 below).
///
/// **NOT in S-034 scope — future stories:**
/// - `child_exit_watch` (natural child exit → `StateChanged{Terminated}` without Kill):
///   implemented in S-039/S-040 (PTY output pipeline; PTY master EOF signals child exit).
/// - Full `tokio::select!` covering both the accept-loop and a PTY reader: also
///   S-039/S-040+ scope (requires a running PTY reader to select over).
/// - PTY bytes forwarding (`HostToDaemon::PtyBytes` fan-out): S-039/S-046.
///
/// **Invariants:**
/// 1. At most one active control connection at a time.
/// 2. SO_PEERCRED check on EVERY accepted connection BEFORE any I/O.
/// 3. Socket file removed ONLY on Kill (not on Detach/EOF).
/// 4. Session-host process survives daemon disconnect/restart (Invariant 5).
///
/// **HIGH-001 (I3-009) startup handshake (sent once on the FIRST accept):**
/// 1. Check `HOME` and `PATH` in the current process environment.
/// 2. If any are missing: send `StateChanged { Launching, degraded_env: Some([...]) }` first.
/// 3. Send `StateChanged { Running, degraded_env: None }` to signal readiness.
///
/// Apply a PTY resize and parser resize in response to `DaemonToHost::Resize`.
///
/// Implements BC-2.09.006 PC-6/PC-7:
/// 1. Calls `pty_master.resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })`,
///    which triggers `SIGWINCH` to the harness child via `portable-pty` (PC-7).
/// 2. Calls `parser.set_size(rows, cols)` to keep the session-host's local vt100 parser
///    in sync with the new PTY dimensions (PC-6).
///
/// On `pty_master.resize()` error: logs at WARN and returns `Err(SessionHostError::Io(...))`.
pub(crate) fn apply_resize_to_pty_and_parser(
    pty_master: &dyn portable_pty::MasterPty,
    parser: &mut vt100::Parser,
    rows: u16,
    cols: u16,
) -> Result<(), SessionHostError> {
    // PC-7: resize PTY master → triggers SIGWINCH to harness child via portable-pty.
    pty_master
        .resize(portable_pty::PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|e| {
            tracing::warn!(
                rows = rows,
                cols = cols,
                error = %e,
                "apply_resize_to_pty_and_parser: pty_master.resize() failed (EC-238)"
            );
            SessionHostError::Io(std::io::Error::other(e))
        })?;

    // PC-6: keep session-host's local vt100 parser in sync.
    // `set_size` lives on `vt100::Screen`, accessed via `parser.screen_mut()`.
    parser.screen_mut().set_size(rows, cols);

    tracing::trace!(
        rows = rows,
        cols = cols,
        "apply_resize_to_pty_and_parser: PTY and parser resized"
    );

    Ok(())
}

/// **MED-003 (SIGKILL reap):** After SIGKILL escalation, a blocking `waitpid` reaps
/// the child PID to prevent zombies. The normal exit path (SIGTERM succeeds) is already
/// reaped by `run()` via `child.wait()` after this function returns.
pub(crate) async fn step_event_loop(
    session_id: &str,
    listener: tokio::net::UnixListener,
    child_pid: u32,
    socket_path: std::path::PathBuf,
    pty_master: Box<dyn portable_pty::MasterPty + Send>,
    parser: &mut vt100::Parser,
) -> Result<(), SessionHostError> {
    use tokio::io::AsyncReadExt;

    // Track whether the degraded-env handshake has been sent (sent only on FIRST accept).
    let mut first_accept = true;

    // -------------------------------------------------------------------------
    // Outer loop: Phase A — Detached, accept-loop.
    // Each iteration either transitions to Phase B (active connection) or exits.
    // -------------------------------------------------------------------------
    loop {
        // -----------------------------------------------------------------------
        // Phase A: wait for daemon to connect (accept-loop).
        // In the future (S-047) this select! will also cover pty_reader.recv().
        // For S-034 scope we only watch the listener.
        // -----------------------------------------------------------------------
        tracing::debug!(
            session_id = %session_id,
            "session-host: waiting for daemon control connection (Phase A)"
        );

        let (mut stream, _addr) = match listener.accept().await {
            Ok(pair) => pair,
            Err(e) => {
                tracing::warn!(
                    session_id = %session_id,
                    error = %e,
                    "session-host: listener.accept() failed — exiting"
                );
                return Err(SessionHostError::UdsBindFailed {
                    path: format!("session-{session_id}.sock"),
                    reason: format!("accept failed: {e}"),
                });
            }
        };

        tracing::debug!(
            session_id = %session_id,
            "session-host: daemon connected to control socket"
        );

        // -------------------------------------------------------------------
        // SO_PEERCRED check on EVERY accepted connection (Invariant 2).
        // UID mismatch: close and loop back to accept.
        // -------------------------------------------------------------------
        if let Err(e) = verify_peer_uid(&stream, session_id) {
            tracing::warn!(
                session_id = %session_id,
                error = %e,
                "session-host: SO_PEERCRED uid mismatch on accept — closing connection, re-accepting"
            );
            drop(stream);
            continue;
        }

        // -------------------------------------------------------------------
        // Phase B: startup handshake (first accept only).
        // -------------------------------------------------------------------
        if first_accept {
            first_accept = false;

            // HIGH-001 (I3-009): check critical env vars; send degraded handshake if missing.
            let critical_vars = ["HOME", "PATH"];
            let missing_vars: Vec<String> = critical_vars
                .iter()
                .filter(|&&var| std::env::var(var).is_err())
                .map(|&var| var.to_string())
                .collect();

            if !missing_vars.is_empty() {
                tracing::warn!(
                    session_id = %session_id,
                    missing = ?missing_vars,
                    "session-host: degraded environment detected — sending Launching+degraded handshake (I3-009)"
                );
                let degraded_msg = monocle_ipc::types::HostToDaemon::StateChanged {
                    new_state: monocle_ipc::types::SessionState::Launching,
                    degraded_env: Some(missing_vars),
                };
                send_host_msg(&mut stream, &degraded_msg).await?;
            }

            // Send HostToDaemon::StateChanged{Running}.
            // degraded_env is always None on the Running message.
            let running_msg = monocle_ipc::types::HostToDaemon::StateChanged {
                new_state: monocle_ipc::types::SessionState::Running,
                degraded_env: None,
            };
            send_host_msg(&mut stream, &running_msg).await?;

            tracing::info!(
                session_id = %session_id,
                "session-host: sent StateChanged{{Running}} to daemon"
            );
        }

        // -------------------------------------------------------------------
        // Phase B: active connection — message dispatch loop.
        // S-034 handles Kill and Detach (+ EOF); S-035 adds Attach; S-042 adds Resize; S-047 adds KeyInput.
        // Returns PhaseBExit to indicate whether to exit or re-accept.
        // -------------------------------------------------------------------
        let phase_b_exit: PhaseBExit = loop {
            let mut len_buf = [0u8; 4];
            match stream.read_exact(&mut len_buf).await {
                Ok(_) => {
                    let msg_len = u32::from_le_bytes(len_buf) as usize;
                    if msg_len == 0 || msg_len > MAX_FRAME_LEN {
                        tracing::warn!(
                            session_id = %session_id,
                            msg_len = msg_len,
                            "session-host: invalid DaemonToHost frame length — closing connection"
                        );
                        break PhaseBExit::Detach;
                    }
                    let mut body = vec![0u8; msg_len];
                    if let Err(e) = stream.read_exact(&mut body).await {
                        tracing::warn!(
                            session_id = %session_id,
                            error = %e,
                            "session-host: failed to read DaemonToHost frame body"
                        );
                        break PhaseBExit::Detach;
                    }

                    match serde_json::from_slice::<monocle_ipc::types::DaemonToHost>(&body) {
                        Ok(monocle_ipc::types::DaemonToHost::Kill) => {
                            // BC-2.08.003 AC-003: Kill sequence.
                            // Runs kill_sequence on `stream`, then exits the process.
                            kill_sequence(session_id, child_pid, &socket_path, &mut stream).await;
                            break PhaseBExit::Kill;
                        }
                        Ok(monocle_ipc::types::DaemonToHost::Detach) => {
                            // SS-session-manager.md §Phase B:
                            // Detach → drop connection, loop back to Phase A.
                            tracing::debug!(
                                session_id = %session_id,
                                "session-host: received DaemonToHost::Detach — returning to Phase A"
                            );
                            break PhaseBExit::Detach;
                        }
                        // S-035: Attach handler (BC-2.08.007 §session-host Attach handler).
                        //
                        // Sends the scrollback dump: zero ScrollbackChunk messages (vt100 PTY
                        // processing is S-047 scope; no screen state exists yet), then
                        // ScrollbackDumpComplete to complete the protocol handshake.
                        //
                        // I3-003 (no pause): PtyBytes forwarding is also S-047 scope, so
                        // resuming live PtyBytes is a no-op here. The daemon's proxy task will
                        // handle PtyBytes once S-047 lands.
                        //
                        // PTY dimensions: hardcoded 24×80 (initial size from Step 3).
                        // S-047 will derive these from the live parser state.
                        Ok(monocle_ipc::types::DaemonToHost::Attach) => {
                            tracing::debug!(
                                session_id = %session_id,
                                "session-host: received DaemonToHost::Attach — sending empty scrollback dump"
                            );
                            // Send ScrollbackDumpComplete (0 chunks — no PTY state yet, S-047 scope).
                            let complete_msg =
                                monocle_ipc::types::HostToDaemon::ScrollbackDumpComplete {
                                    total_chunks: 0,
                                    cursor_row: 0,
                                    cursor_col: 0,
                                    pty_rows: 24,
                                    pty_cols: 80,
                                };
                            if let Err(e) = send_host_msg(&mut stream, &complete_msg).await {
                                tracing::warn!(
                                    session_id = %session_id,
                                    error = %e,
                                    "session-host: failed to send ScrollbackDumpComplete on Attach"
                                );
                                break PhaseBExit::Detach;
                            }
                            tracing::debug!(
                                session_id = %session_id,
                                "session-host: ScrollbackDumpComplete sent (total_chunks=0)"
                            );
                            // Continue Phase B — await next message (Detach/Kill/etc.).
                        }
                        // BC-2.09.006 PC-6/PC-7: resize the PTY and local parser
                        // (S-042 scope per human ruling 2026-06-21).
                        Ok(monocle_ipc::types::DaemonToHost::Resize { rows, cols }) => {
                            if let Err(e) = apply_resize_to_pty_and_parser(
                                pty_master.as_ref(),
                                parser,
                                rows,
                                cols,
                            ) {
                                tracing::warn!(
                                    session_id = %session_id,
                                    rows = rows,
                                    cols = cols,
                                    error = %e,
                                    "session-host: DaemonToHost::Resize failed — continuing"
                                );
                            }
                        }
                        Ok(_other) => {
                            // KeyInput — S-047 scope. Other unknown variants are also ignored.
                            tracing::debug!(
                                session_id = %session_id,
                                "session-host: received unhandled DaemonToHost message (S-047 scope), ignoring"
                            );
                        }
                        Err(e) => {
                            tracing::warn!(
                                session_id = %session_id,
                                error = %e,
                                "session-host: failed to deserialize DaemonToHost message — closing connection"
                            );
                            break PhaseBExit::Detach;
                        }
                    }
                }
                Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => {
                    // EOF: daemon side closed without sending Detach (crash/restart).
                    // SS-session-manager.md §Invariant 5: loop back to Phase A.
                    tracing::debug!(
                        session_id = %session_id,
                        "session-host: daemon closed control connection (EOF) — returning to Phase A"
                    );
                    break PhaseBExit::Detach;
                }
                Err(e) => {
                    tracing::warn!(
                        session_id = %session_id,
                        error = %e,
                        "session-host: control connection read error — returning to Phase A"
                    );
                    break PhaseBExit::Detach;
                }
            }
        };
        // Drop stream (connection) before deciding next action.
        drop(stream);

        match phase_b_exit {
            PhaseBExit::Kill => {
                // kill_sequence has already run; exit the process.
                return Ok(());
            }
            PhaseBExit::Detach => {
                // Loop back to Phase A: re-accept the next daemon connection.
                continue;
            }
        }
    }
}

/// Reason a Phase B active connection ended.
enum PhaseBExit {
    /// Kill received and kill_sequence completed: exit the process.
    Kill,
    /// Detach, EOF, or error: loop back to Phase A (re-accept).
    Detach,
}

/// Pure comparison kernel for SO_PEERCRED UID validation (IMP-002 test seam).
///
/// Separated from `verify_peer_uid` so the reject-on-mismatch branch can be
/// unit-tested with synthetic UID pairs without requiring elevated OS privileges.
/// Production semantics are identical: `verify_peer_uid` calls this function
/// after obtaining the real peer and own UIDs from the OS.
///
/// Returns `Ok(())` when `peer_uid == own_uid`; `Err(PermissionDenied)` otherwise.
pub(crate) fn check_peer_uid(peer_uid: u32, own_uid: u32) -> Result<(), SessionHostError> {
    if peer_uid != own_uid {
        return Err(SessionHostError::Io(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            format!("SO_PEERCRED uid mismatch: peer={peer_uid} own={own_uid}"),
        )));
    }
    Ok(())
}

/// Verify that the peer UID of the connected socket matches the current process UID.
///
/// Uses tokio's `UnixStream::peer_cred()` which calls `SO_PEERCRED` on Linux and
/// `LOCAL_PEERCRED` (getpeereid) on macOS.
/// Returns `Ok(())` if the UIDs match; `Err(...)` on mismatch or platform error.
fn verify_peer_uid(
    stream: &tokio::net::UnixStream,
    session_id: &str,
) -> Result<(), SessionHostError> {
    let peer_uid = stream
        .peer_cred()
        .map(|c| c.uid())
        .map_err(SessionHostError::Io)?;
    let own_uid = nix::unistd::getuid().as_raw();

    if peer_uid != own_uid {
        tracing::warn!(
            session_id = %session_id,
            peer_uid = peer_uid,
            own_uid = own_uid,
            "session-host: SO_PEERCRED uid mismatch"
        );
    }
    check_peer_uid(peer_uid, own_uid)
}

/// Kill sequence: SIGTERM → 10s waitpid → SIGKILL (+ reap) → StateChanged{Terminated}
/// → Goodbye → remove socket file.
///
/// Called from Phase B when `DaemonToHost::Kill` is received.
///
/// **MED-003:** After SIGKILL escalation the child PID is reaped via a best-effort
/// `waitpid(WNOHANG)` call (non-blocking immediate check). If the child has not yet
/// exited by that point a 200 ms sleep + second WNOHANG attempt is made. The
/// guaranteed backstop against zombie accumulation is `run()`'s blocking `child.wait()`
/// after the event loop returns. The SIGTERM exit path is also reaped by that same
/// `child.wait()` — `kill_sequence` only needs to attempt an early reap on the SIGKILL
/// path so that `run()`'s subsequent `child.wait()` reliably gets `ECHILD` rather than
/// blocking on an already-dead process.
pub(crate) async fn kill_sequence(
    session_id: &str,
    child_pid: u32,
    socket_path: &std::path::Path,
    stream: &mut tokio::net::UnixStream,
) {
    use nix::sys::signal::{kill as nix_kill, Signal};
    use nix::unistd::Pid;
    let nix_pid = Pid::from_raw(child_pid as i32);

    // a. SIGTERM
    if let Err(e) = nix_kill(nix_pid, Signal::SIGTERM) {
        tracing::warn!(
            session_id = %session_id,
            pid = child_pid,
            error = %e,
            "session-host: SIGTERM to harness child failed"
        );
    } else {
        tracing::debug!(
            session_id = %session_id,
            pid = child_pid,
            "session-host: sent SIGTERM to harness child"
        );
    }

    // b. Wait up to SIGTERM_TIMEOUT_MS (default 10 000ms = 10s) for child exit.
    //
    // Implementation: async polling loop — each iteration calls waitpid(WNOHANG)
    // via spawn_blocking (short, non-blocking syscall), then yields via
    // tokio::time::sleep(100ms) between polls. This keeps the blocking thread
    // pool free between polls and lets tokio::time::advance() fire the outer
    // timeout when running under #[tokio::test(start_paused=true)].
    //
    // Production behavior is byte-for-byte equivalent to the previous
    // spawn_blocking loop: 100ms inter-poll interval, 10s total window, then
    // SIGKILL escalation. The only change is that the sleep is driven by the
    // tokio runtime clock rather than a blocking OS thread sleep, which makes
    // the timeout virtualizable in tests without altering wall-clock behavior
    // in production.
    #[cfg(test)]
    let sigterm_timeout = std::time::Duration::from_millis(
        SIGTERM_TIMEOUT_MS.load(std::sync::atomic::Ordering::Relaxed),
    );
    #[cfg(not(test))]
    let sigterm_timeout = std::time::Duration::from_secs(10);

    let child_exited = tokio::time::timeout(sigterm_timeout, async move {
        use nix::sys::wait::{waitpid, WaitPidFlag, WaitStatus};
        loop {
            // One WNOHANG waitpid check (fast blocking syscall — < 1µs typical).
            let still_alive = tokio::task::spawn_blocking(move || {
                matches!(
                    waitpid(nix_pid, Some(WaitPidFlag::WNOHANG)),
                    Ok(WaitStatus::StillAlive)
                )
            })
            .await
            // spawn_blocking JoinError should not happen in normal operation.
            .unwrap_or(false);

            if !still_alive {
                return true;
            }
            // Yield for 100ms using tokio time — allows tokio::time::advance()
            // to fire the outer timeout in test environments (start_paused=true).
            tokio::time::sleep(std::time::Duration::from_millis(100)).await;
        }
    })
    .await;

    if child_exited.is_err() {
        // 10s elapsed without exit — escalate to SIGKILL.
        tracing::warn!(
            session_id = %session_id,
            pid = child_pid,
            "session-host: harness child did not exit within 10s — sending SIGKILL"
        );
        nix_kill(nix_pid, Signal::SIGKILL).ok();

        // MED-003: reap the child after SIGKILL to prevent zombie.
        // run() will call child.wait() later but portable_pty's child handle may not
        // map to the same PID after a SIGKILL on all platforms. We use a direct blocking
        // waitpid to guarantee reap. Ignore ECHILD if already reaped.
        tokio::task::spawn_blocking(move || {
            use nix::sys::wait::{waitpid, WaitPidFlag};
            match waitpid(nix_pid, Some(WaitPidFlag::WNOHANG)) {
                // Immediate check: if already reaped, fine.
                Ok(_) => {}
                Err(nix::errno::Errno::ECHILD) => {} // already gone — ok
                Err(_) => {
                    // Best-effort: small sleep then final waitpid attempt.
                    std::thread::sleep(std::time::Duration::from_millis(200));
                    let _ = waitpid(nix_pid, Some(WaitPidFlag::WNOHANG));
                }
            }
        })
        .await
        .ok();
    }

    // c. Notify daemon: session transitioned to Terminated.
    let terminated_msg = monocle_ipc::types::HostToDaemon::StateChanged {
        new_state: monocle_ipc::types::SessionState::Terminated,
        degraded_env: None,
    };
    if let Err(e) = send_host_msg(stream, &terminated_msg).await {
        tracing::warn!(
            session_id = %session_id,
            error = %e,
            "session-host: failed to send StateChanged{{Terminated}}"
        );
    }

    // d. Send Goodbye to signal clean close of control connection.
    let goodbye_msg = monocle_ipc::types::HostToDaemon::Goodbye;
    if let Err(e) = send_host_msg(stream, &goodbye_msg).await {
        tracing::warn!(
            session_id = %session_id,
            error = %e,
            "session-host: failed to send Goodbye"
        );
    }

    // e. Remove UDS socket file (clean up per-session socket).
    if let Err(e) = std::fs::remove_file(socket_path) {
        tracing::warn!(
            session_id = %session_id,
            path = %socket_path.display(),
            error = %e,
            "session-host: failed to remove UDS socket file after Kill"
        );
    }

    tracing::info!(
        session_id = %session_id,
        "session-host: Kill sequence complete"
    );
}

// ---------------------------------------------------------------------------
// Test-visibility hook: configurable SIGTERM timeout (cfg(test) only).
//
// Production default is always 10_000ms (10s). Under cfg(test), tests may
// write a shorter value via SIGTERM_TIMEOUT_MS before calling kill_sequence
// so tokio::time::advance() can fire the timeout without a real wall-clock
// wait. This static is NEVER read in production builds (cfg(test) guard).
// ---------------------------------------------------------------------------
#[cfg(test)]
static SIGTERM_TIMEOUT_MS: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(10_000);

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(non_snake_case)]
mod tests {
    use super::*;
    use monocle_ipc::types::{DaemonToHost, HostToDaemon, SessionState};
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    // -----------------------------------------------------------------------
    // Test helpers
    // -----------------------------------------------------------------------

    /// Read one length-prefixed JSON frame from a `UnixStream` and deserialize as `HostToDaemon`.
    async fn read_host_msg(stream: &mut tokio::net::UnixStream) -> HostToDaemon {
        let mut len_buf = [0u8; 4];
        stream
            .read_exact(&mut len_buf)
            .await
            .expect("read_host_msg: failed to read length prefix");
        let len = u32::from_le_bytes(len_buf) as usize;
        let mut body = vec![0u8; len];
        stream
            .read_exact(&mut body)
            .await
            .expect("read_host_msg: failed to read body");
        serde_json::from_slice::<HostToDaemon>(&body)
            .expect("read_host_msg: failed to deserialize HostToDaemon")
    }

    /// Write one `DaemonToHost` message as a length-prefixed JSON frame.
    async fn write_daemon_msg(stream: &mut tokio::net::UnixStream, msg: &DaemonToHost) {
        let body = serde_json::to_vec(msg).expect("write_daemon_msg: serialize failed");
        let len = body.len() as u32;
        stream
            .write_all(&len.to_le_bytes())
            .await
            .expect("write_daemon_msg: write len failed");
        stream
            .write_all(&body)
            .await
            .expect("write_daemon_msg: write body failed");
        stream
            .flush()
            .await
            .expect("write_daemon_msg: flush failed");
    }

    /// Unique socket path under /tmp for a test run.
    fn tmp_sock(label: &str) -> std::path::PathBuf {
        std::path::PathBuf::from(format!(
            "/tmp/monocle-test-{}-{}.sock",
            label,
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .subsec_nanos()
        ))
    }

    // -----------------------------------------------------------------------
    // Test 1: BC-2.08.003 AC-003 — Kill sequence SIGTERM path (MED-002)
    //
    // Drives the REAL `kill_sequence()` against a real child process (`sleep`).
    // A child that responds to SIGTERM exits within the 10-second window;
    // asserts StateChanged{Terminated} + Goodbye emitted in order; asserts
    // UDS socket file is removed after the sequence completes.
    // -----------------------------------------------------------------------
    /// BC-2.08.003 AC-003 (MED-002): kill_sequence sends SIGTERM to a real child,
    /// the child exits within 10s, StateChanged{Terminated} is emitted followed by
    /// Goodbye, and the UDS socket file is removed.
    ///
    /// Drives REAL `kill_sequence()` — not a daemon-side simulation.
    // CR-003: #[serial_test::serial] — this test calls kill_sequence which reads
    // SIGTERM_TIMEOUT_MS; must not run concurrently with tests that mutate it.
    #[serial_test::serial]
    #[tokio::test]
    async fn test_BC_2_08_003_AC003_kill_sequence_sigterm_child_exits_normally() {
        // Spawn a real child process that will exit cleanly on SIGTERM.
        // `sleep 3600` is the canonical long-running test child; nix SIGTERM → it exits.
        let mut child = std::process::Command::new("sleep")
            .arg("3600")
            .spawn()
            .expect("BC-2.08.003 AC-003 (MED-002): failed to spawn sleep child");
        let child_pid = child.id();

        // Create UDS socket pair: test plays the daemon side.
        let sock_path = tmp_sock("med002-sigterm");
        let _ = std::fs::remove_file(&sock_path);

        let listener = tokio::net::UnixListener::bind(&sock_path)
            .expect("BC-2.08.003 AC-003 (MED-002): bind listener");

        // Connect the "daemon" side before calling kill_sequence.
        let connect_fut = tokio::net::UnixStream::connect(&sock_path);
        let (accept_result, connect_result) = tokio::join!(listener.accept(), connect_fut);
        let (mut session_host_side, _) = accept_result.expect("accept");
        let mut daemon_side = connect_result.expect("connect");

        // Call the REAL kill_sequence: SIGTERM → wait ≤ 10s → emit messages → remove socket.
        // Run kill_sequence in a spawned task (moves session_host_side into it) so we can
        // read from daemon_side concurrently without holding two &mut refs simultaneously.
        let sock_path_clone = sock_path.clone();
        let kill_task = tokio::spawn(async move {
            kill_sequence(
                "test-session-med002",
                child_pid,
                &sock_path_clone,
                &mut session_host_side,
            )
            .await;
        });

        // Read the two messages from the daemon side while kill_sequence runs.
        let msg1 = read_host_msg(&mut daemon_side).await;
        let msg2 = read_host_msg(&mut daemon_side).await;

        // Await kill_task completion.
        kill_task.await.expect("kill_task panicked");

        // Assert: first message is StateChanged{Terminated} (BC-2.08.003 AC-003 step c).
        match msg1 {
            HostToDaemon::StateChanged {
                new_state: SessionState::Terminated,
                ..
            } => {}
            other => panic!(
                "BC-2.08.003 AC-003 (MED-002): expected StateChanged{{Terminated}}, got {:?}",
                other
            ),
        }

        // Assert: second message is Goodbye (BC-2.08.003 AC-003 step d).
        match msg2 {
            HostToDaemon::Goodbye => {}
            other => panic!(
                "BC-2.08.003 AC-003 (MED-002): expected Goodbye, got {:?}",
                other
            ),
        }

        // Assert: socket file removed (BC-2.08.003 AC-003 step e).
        assert!(
            !sock_path.exists(),
            "BC-2.08.003 AC-003 (MED-002): UDS socket file must be removed after Kill sequence"
        );

        // Assert: child is reaped (no zombie).
        // kill_sequence's internal waitpid loop (spawn_blocking) already reaped the child
        // when SIGTERM caused it to exit. `child.wait()` will therefore return ECHILD (OS
        // error 10 on macOS / error 10 on Linux) — which is the proof that the child IS
        // reaped. ECHILD means "no child process" = already reaped = not a zombie.
        // Any other I/O error is a genuine test failure.
        match child.wait() {
            Ok(_status) => {
                // Also fine: child.wait() succeeded — child was reaped (possibly before
                // kill_sequence's waitpid on some timing windows). Not a zombie.
            }
            Err(e) if e.raw_os_error() == Some(nix::errno::Errno::ECHILD as i32) => {
                // ECHILD: kill_sequence's waitpid already reaped the child. Not a zombie.
                // This is the expected path when SIGTERM exits the child before our wait().
            }
            Err(e) => {
                panic!(
                    "BC-2.08.003 AC-003 (MED-002): unexpected child.wait() error (not ECHILD): {}",
                    e
                );
            }
        }
    }

    // -----------------------------------------------------------------------
    // Test 1b: BC-2.08.003 AC-003 — Kill sequence SIGKILL escalation (MED-002)
    //
    // Tests the post-SIGKILL path of kill_sequence: StateChanged{Terminated} +
    // Goodbye + socket removal are correctly emitted even when the child has
    // already been killed externally (simulating the post-SIGKILL state).
    // -----------------------------------------------------------------------

    /// BC-2.08.003 AC-003 (MED-002): kill_sequence correctly emits StateChanged{Terminated},
    /// Goodbye, and removes the socket file when the harness child has already exited
    /// (simulating the post-SIGKILL state). Drives REAL kill_sequence() code.
    ///
    /// This test exercises: SIGTERM delivery to an already-dead child (ESRCH, ignored),
    /// immediate waitpid return (child exited), StateChanged{Terminated} + Goodbye messages,
    /// and socket removal. The 10s SIGKILL escalation path is tested separately (see
    /// the #[ignore] test below).
    // CR-003: #[serial_test::serial] — this test calls kill_sequence which reads
    // SIGTERM_TIMEOUT_MS; must not run concurrently with tests that mutate it.
    #[serial_test::serial]
    #[tokio::test]
    async fn test_BC_2_08_003_AC003_kill_sequence_messages_and_socket_removal_after_child_exit() {
        // Spawn a real child and immediately kill it externally (simulating a child that
        // exits before kill_sequence's waitpid poll — covers the fast-exit path where
        // SIGTERM arrives but child is already dead or exits immediately).
        let mut child = std::process::Command::new("sleep")
            .arg("0")
            .spawn()
            .expect("BC-2.08.003 AC-003 fast-exit (MED-002): failed to spawn sleep 0");
        let child_pid = child.id();
        // Let child exit naturally (sleep 0 exits immediately).
        // Give it a tick to actually exit.
        tokio::task::spawn_blocking(|| {
            std::thread::sleep(std::time::Duration::from_millis(50));
        })
        .await
        .expect("spawn_blocking sleep");

        let sock_path = tmp_sock("med002-fast-exit");
        let _ = std::fs::remove_file(&sock_path);

        let listener = tokio::net::UnixListener::bind(&sock_path)
            .expect("BC-2.08.003 AC-003 fast-exit (MED-002): bind listener");

        let connect_fut = tokio::net::UnixStream::connect(&sock_path);
        let (accept_result, connect_result) = tokio::join!(listener.accept(), connect_fut);
        let (mut session_host_side, _) = accept_result.expect("accept");
        let mut daemon_side = connect_result.expect("connect");

        // Run kill_sequence against a child that has already exited.
        // This tests the WNOHANG waitpid path where child is immediately reaped.
        let sock_path_clone = sock_path.clone();
        let kill_task = tokio::spawn(async move {
            kill_sequence(
                "test-session-med002-fast-exit",
                child_pid,
                &sock_path_clone,
                &mut session_host_side,
            )
            .await;
        });

        // Read messages: kill_sequence should emit StateChanged{Terminated} + Goodbye quickly.
        let msg1 = read_host_msg(&mut daemon_side).await;
        let msg2 = read_host_msg(&mut daemon_side).await;

        kill_task.await.expect("kill_task panicked");

        // Assert: StateChanged{Terminated} emitted (BC-2.08.003 AC-003 step c).
        match msg1 {
            HostToDaemon::StateChanged {
                new_state: SessionState::Terminated,
                ..
            } => {}
            other => panic!(
                "BC-2.08.003 AC-003 fast-exit (MED-002): expected StateChanged{{Terminated}}, got {:?}",
                other
            ),
        }

        // Assert: Goodbye emitted (BC-2.08.003 AC-003 step d).
        match msg2 {
            HostToDaemon::Goodbye => {}
            other => panic!(
                "BC-2.08.003 AC-003 fast-exit (MED-002): expected Goodbye, got {:?}",
                other
            ),
        }

        // Assert: socket file removed (BC-2.08.003 AC-003 step e).
        assert!(
            !sock_path.exists(),
            "BC-2.08.003 AC-003 fast-exit (MED-002): UDS socket file must be removed after Kill sequence"
        );

        // Reap child: kill_sequence's waitpid may have already reaped it (ECHILD is fine).
        match child.wait() {
            Ok(_) => {}
            Err(e) if e.raw_os_error() == Some(nix::errno::Errno::ECHILD as i32) => {}
            Err(e) => panic!(
                "BC-2.08.003 AC-003 fast-exit: unexpected child.wait() error: {}",
                e
            ),
        }
    }

    // -----------------------------------------------------------------------
    // Test 1c: BC-2.08.003 AC-003 — SIGKILL escalation on SIGTERM timeout
    //
    // Full escalation path: child ignores SIGTERM → SIGTERM window expires →
    // SIGKILL delivered → child reaped → StateChanged{Terminated} + Goodbye
    // emitted → socket removed.
    //
    // Enabled by the SIGTERM_TIMEOUT_MS test-visibility hook: the test sets the
    // timeout to 1s (1000ms) so tokio::time::advance() can fire it instantly
    // without a real wall-clock wait. Production code path (10_000ms) is
    // preserved via the #[cfg(not(test))] branch.
    // -----------------------------------------------------------------------

    /// BC-2.08.003 AC-003 (MED-002): when child ignores SIGTERM, kill_sequence
    /// escalates to SIGKILL after the timeout window expires. Asserts:
    /// - SIGTERM is sent (child survives because it has a no-op trap).
    /// - SIGKILL is delivered after the window.
    /// - Child is reaped (no zombie): child.wait() returns ECHILD or a status.
    /// - StateChanged{Terminated} emitted after SIGKILL path.
    /// - Goodbye emitted.
    /// - UDS socket file removed.
    ///
    /// Uses SIGTERM_TIMEOUT_MS hook (1s) + tokio::time::advance(2s) to exercise
    /// the full SIGKILL escalation branch without a real 10s wall-clock wait.
    // CR-003: #[serial_test::serial] required because this test mutates the package-level
    // SIGTERM_TIMEOUT_MS AtomicU64 global. Running concurrently with other tests that read
    // SIGTERM_TIMEOUT_MS at its default (10_000ms) would cause flaky failures.
    #[serial_test::serial]
    #[tokio::test(start_paused = true)]
    async fn test_BC_2_08_003_AC003_kill_sequence_sigkill_escalation_on_timeout() {
        // Set SIGTERM timeout to 1s for this test (hook value; production default is 10s).
        // Relaxed ordering is safe: single-threaded setup before task spawn.
        SIGTERM_TIMEOUT_MS.store(1_000, std::sync::atomic::Ordering::Relaxed);

        // Spawn a real child that ignores SIGTERM so kill_sequence must escalate to SIGKILL.
        // `sh -c 'trap "" TERM; sleep 3600'` sets a no-op SIGTERM handler and sleeps.
        let mut child = std::process::Command::new("sh")
            .args(["-c", "trap '' TERM; sleep 3600"])
            .spawn()
            .expect("BC-2.08.003 AC-003 SIGKILL (MED-002): failed to spawn SIGTERM-ignoring child");
        let child_pid = child.id();

        // Give the shell a moment to establish its trap before we send SIGTERM.
        // spawn_blocking ensures the real OS thread sleep runs on the blocking pool
        // (not the tokio reactor thread), keeping the async runtime responsive.
        tokio::task::spawn_blocking(|| {
            std::thread::sleep(std::time::Duration::from_millis(200));
        })
        .await
        .expect("spawn_blocking setup sleep");

        let sock_path = tmp_sock("med002-sigkill");
        let _ = std::fs::remove_file(&sock_path);

        let listener = tokio::net::UnixListener::bind(&sock_path)
            .expect("BC-2.08.003 AC-003 SIGKILL (MED-002): bind listener");

        let connect_fut = tokio::net::UnixStream::connect(&sock_path);
        let (accept_result, connect_result) = tokio::join!(listener.accept(), connect_fut);
        let (mut session_host_side, _) = accept_result.expect("accept");
        let mut daemon_side = connect_result.expect("connect");

        // Assert: child is alive before kill_sequence runs (verifies SIGTERM-ignoring
        // trap is effective — child survives the initial SIGTERM delivery).
        {
            use nix::sys::signal::{kill as nix_kill, Signal};
            use nix::unistd::Pid;
            let probe_pid = Pid::from_raw(child_pid as i32);
            // kill(pid, 0) is the POSIX "process exists?" probe — signal 0 is never delivered.
            assert!(
                nix_kill(probe_pid, Signal::SIGTERM).is_ok()
                    || nix::errno::Errno::last() != nix::errno::Errno::ESRCH,
                "BC-2.08.003 AC-003 SIGKILL: child must be alive before kill_sequence"
            );
        }

        // Run kill_sequence in a task so we can advance time concurrently.
        // kill_sequence uses the SIGTERM_TIMEOUT_MS hook (1s) so advance(2s) fires it.
        let sock_path_clone = sock_path.clone();
        let kill_task = tokio::spawn(async move {
            kill_sequence(
                "test-session-med002-sigkill",
                child_pid,
                &sock_path_clone,
                &mut session_host_side,
            )
            .await;
        });

        // Yield once to let kill_sequence send SIGTERM and enter the async poll loop.
        tokio::task::yield_now().await;

        // Advance tokio virtual time past the 1s SIGTERM window.
        // The async poll loop uses tokio::time::sleep(100ms) between waitpid polls,
        // so advance() moves the clock forward without any real wall-clock wait.
        tokio::time::advance(std::time::Duration::from_secs(2)).await;

        // Read the two messages — kill_sequence emits them after SIGKILL + reap.
        let msg1 = read_host_msg(&mut daemon_side).await;
        let msg2 = read_host_msg(&mut daemon_side).await;

        kill_task.await.expect("kill_task did not complete");

        // Assert: first message is StateChanged{Terminated} (BC-2.08.003 AC-003 step c).
        match msg1 {
            HostToDaemon::StateChanged {
                new_state: SessionState::Terminated,
                ..
            } => {}
            other => panic!(
                "BC-2.08.003 AC-003 SIGKILL (MED-002): expected StateChanged{{Terminated}}, got {:?}",
                other
            ),
        }

        // Assert: second message is Goodbye (BC-2.08.003 AC-003 step d).
        match msg2 {
            HostToDaemon::Goodbye => {}
            other => panic!(
                "BC-2.08.003 AC-003 SIGKILL (MED-002): expected Goodbye, got {:?}",
                other
            ),
        }

        // Assert: socket file removed (BC-2.08.003 AC-003 step e).
        assert!(
            !sock_path.exists(),
            "BC-2.08.003 AC-003 SIGKILL (MED-002): UDS socket file must be removed after SIGKILL path"
        );

        // Assert: child is reaped (no zombie).
        // kill_sequence's post-SIGKILL waitpid already reaped the child.
        // child.wait() returning ECHILD or a status both prove "not a zombie".
        match child.wait() {
            Ok(_status) => {
                // child.wait() succeeded — child reaped. Not a zombie.
            }
            Err(e) if e.raw_os_error() == Some(nix::errno::Errno::ECHILD as i32) => {
                // ECHILD: kill_sequence's waitpid already reaped the child. Not a zombie.
            }
            Err(e) => {
                panic!(
                    "BC-2.08.003 AC-003 SIGKILL (MED-002): unexpected child.wait() error (not ECHILD): {}",
                    e
                );
            }
        }

        // Reset SIGTERM_TIMEOUT_MS to production default so other tests are unaffected.
        SIGTERM_TIMEOUT_MS.store(10_000, std::sync::atomic::Ordering::Relaxed);
    }

    // -----------------------------------------------------------------------
    // Test 2: Accept-loop re-accept regression guard (BLOCKER-001-guard)
    //
    // Drives the REAL `step_event_loop()`: conn #1 → Phase B → Detach → Phase A
    // → re-accept → conn #2 → Kill → process exits.
    //
    // This is the test that would have caught the single-accept defect that
    // ADV-S034-BLOCKER-001 identified. It drives REAL step_event_loop code.
    // -----------------------------------------------------------------------
    /// BLOCKER-001-guard: step_event_loop must return to Phase A after Detach and
    /// accept a second connection. The kill on the second connection must work correctly.
    ///
    /// Drives REAL `step_event_loop()` — drives the two-phase loop with real sockets
    /// and a real child process.
    // CR-003: #[serial_test::serial] — this test drives step_event_loop which calls
    // kill_sequence (reads SIGTERM_TIMEOUT_MS); must not run concurrently with tests
    // that mutate it.
    #[serial_test::serial]
    #[tokio::test]
    async fn test_BC_2_08_003_accept_loop_re_accept_after_detach_BLOCKER001_guard() {
        // Spawn a real child process that survives across the Detach/re-accept cycle.
        let mut child = std::process::Command::new("sleep")
            .arg("3600")
            .spawn()
            .expect("BLOCKER-001-guard: failed to spawn sleep child");
        let child_pid = child.id();

        let sock_path = tmp_sock("blocker001");
        let _ = std::fs::remove_file(&sock_path);
        let sock_path_for_loop = sock_path.clone();

        // Bind the listener that step_event_loop will use.
        let listener =
            tokio::net::UnixListener::bind(&sock_path).expect("BLOCKER-001-guard: bind listener");

        // Open a PTY pair so step_event_loop has a valid pty_master (needed for DaemonToHost::Resize).
        // The test only sends Kill/Detach so pty_master.resize() is never called; this PTY is
        // plumbing required by the updated step_event_loop signature.
        let pty_system = portable_pty::native_pty_system();
        let pty_pair = pty_system
            .openpty(portable_pty::PtySize {
                rows: 24,
                cols: 80,
                pixel_width: 0,
                pixel_height: 0,
            })
            .expect("BLOCKER-001-guard: openpty for step_event_loop must succeed");

        // Spawn step_event_loop as a task.
        let loop_task = tokio::spawn(async move {
            let mut parser = step_init_vt100_parser(24, 80);
            step_event_loop(
                "test-session-blocker001",
                listener,
                child_pid,
                sock_path_for_loop,
                pty_pair.master,
                &mut parser,
            )
            .await
        });

        // --- Connection #1: connect, receive Running handshake, send Detach ---
        let mut conn1 = tokio::net::UnixStream::connect(&sock_path)
            .await
            .expect("BLOCKER-001-guard: conn1 connect failed");

        // Receive StateChanged{Running} startup handshake (first_accept).
        let running_msg = read_host_msg(&mut conn1).await;
        match running_msg {
            HostToDaemon::StateChanged {
                new_state: SessionState::Running,
                ..
            } => {}
            other => panic!(
                "BLOCKER-001-guard: conn1 expected StateChanged{{Running}}, got {:?}",
                other
            ),
        }

        // Send Detach to trigger Phase A re-accept (SS-session-manager.md §Phase B).
        write_daemon_msg(&mut conn1, &DaemonToHost::Detach).await;
        drop(conn1);

        // Give the event loop a tick to process the Detach and return to Phase A.
        tokio::task::yield_now().await;

        // --- Connection #2: connect and send Kill ---
        // BLOCKER-001-guard: if the loop only accepted once, this connect would hang forever.
        let mut conn2 = tokio::time::timeout(
            std::time::Duration::from_secs(2),
            tokio::net::UnixStream::connect(&sock_path),
        )
        .await
        .expect("BLOCKER-001-guard: conn2 timed out — step_event_loop did NOT re-accept (BLOCKER-001 regressed!)")
        .expect("BLOCKER-001-guard: conn2 connect failed");

        // Send Kill on conn2.
        write_daemon_msg(&mut conn2, &DaemonToHost::Kill).await;

        // Receive StateChanged{Terminated} + Goodbye from kill_sequence.
        let term_msg = read_host_msg(&mut conn2).await;
        match term_msg {
            HostToDaemon::StateChanged {
                new_state: SessionState::Terminated,
                ..
            } => {}
            other => panic!(
                "BLOCKER-001-guard: conn2 expected StateChanged{{Terminated}}, got {:?}",
                other
            ),
        }
        let goodbye_msg = read_host_msg(&mut conn2).await;
        match goodbye_msg {
            HostToDaemon::Goodbye => {}
            other => panic!("BLOCKER-001-guard: conn2 expected Goodbye, got {:?}", other),
        }
        drop(conn2);

        // step_event_loop returns Ok(()) after Kill. Assert it completes within 2s.
        tokio::time::timeout(std::time::Duration::from_secs(2), loop_task)
            .await
            .expect("BLOCKER-001-guard: step_event_loop task timed out")
            .expect("BLOCKER-001-guard: step_event_loop task panicked")
            .expect("BLOCKER-001-guard: step_event_loop returned Err");

        // Reap child (kill_sequence sent SIGTERM/SIGKILL).
        let _ = child.wait();
    }

    // -----------------------------------------------------------------------
    // Test 3: SO_PEERCRED on accept — AC-009 acceptor side
    //
    // verify_peer_uid() is private but accessible from this inner module via
    // `super::verify_peer_uid`. Tests:
    // (a) Same-UID connection is accepted (positive case — our own UID).
    // (b) Structural test: verify_peer_uid returns Err on a stream whose peer_cred()
    //     uid != own_uid. We simulate the mismatch by checking the logic branch
    //     directly — the function correctly rejects mismatches.
    //
    // Note: A true UID-mismatch test requires running as root or a different OS user,
    // which is not possible in a standard CI environment. We therefore test:
    // - The positive case (same-user connect is accepted — correct UID passes).
    // - The control-flow: by reading the function's guard condition directly.
    // The integration-level assertion (that loop continues on reject) is covered
    // by the accept-loop test above where a valid same-UID conn #2 succeeds AFTER
    // conn #1 was processed.
    // -----------------------------------------------------------------------
    /// AC-009 (acceptor side): verify_peer_uid accepts connections from the same UID.
    ///
    /// Exercises the REAL `verify_peer_uid()` function. Same-process connections
    /// always have matching UIDs, so this tests the happy path. The function is
    /// accessible via `super::` from within the test module.
    #[tokio::test]
    async fn test_BC_2_08_003_AC009_so_peercred_same_uid_accepted() {
        let sock_path = tmp_sock("ac009-same-uid");
        let _ = std::fs::remove_file(&sock_path);

        let listener = tokio::net::UnixListener::bind(&sock_path).expect("AC-009: bind listener");

        let connect_fut = tokio::net::UnixStream::connect(&sock_path);
        let (accept_result, connect_result) = tokio::join!(listener.accept(), connect_fut);
        let (server_stream, _) = accept_result.expect("AC-009: accept failed");
        let _client_stream = connect_result.expect("AC-009: connect failed");

        // Assert: verify_peer_uid returns Ok for a same-process (same-UID) connection.
        // BC-2.08.003 Invariant 5: SO_PEERCRED on every accept. Same-UID = Ok.
        let result = verify_peer_uid(&server_stream, "test-session-ac009");
        assert!(
            result.is_ok(),
            "AC-009 (BC-2.08.003 Invariant 5): verify_peer_uid must return Ok for same-UID connection; got: {:?}",
            result.err()
        );

        let _ = std::fs::remove_file(&sock_path);
    }

    /// AC-009 (acceptor side): verify_peer_uid wires peer_cred() correctly — same-UID
    /// connections are accepted and peer_cred() returns the current process UID.
    ///
    /// This test validates the POSITIVE path only: that peer_cred() yields own_uid for
    /// a self-connect, and that verify_peer_uid accepts it.  The NEGATIVE path
    /// (peer_uid != own_uid → PermissionDenied) is covered by the pure unit tests for
    /// `check_peer_uid` below (test_BC_2_08_003_IMP002_*).
    ///
    /// Renamed from `test_BC_2_08_003_AC009_so_peercred_uid_mismatch_returns_permission_denied`
    /// (misleading: the old name implied a mismatch was tested here; it was not).
    /// All original assertions are preserved, no weakening — F-S034-ADV-IMP-002.
    #[tokio::test]
    async fn test_BC_2_08_003_AC009_so_peercred_peer_cred_wiring_same_uid_accepted() {
        // We verify the structural guard: own_uid is correctly obtained via nix::unistd::getuid().
        let own_uid = nix::unistd::getuid().as_raw();

        // A self-connect always returns the current process UID as peer_uid.
        // Verify that own_uid matches what we get from a real peer_cred() call.
        let sock_path = tmp_sock("ac009-uid-check");
        let _ = std::fs::remove_file(&sock_path);

        let listener =
            tokio::net::UnixListener::bind(&sock_path).expect("AC-009 uid-check: bind listener");

        let (accept_result, connect_result) = tokio::join!(
            listener.accept(),
            tokio::net::UnixStream::connect(&sock_path)
        );
        let (server_stream, _) = accept_result.expect("accept");
        // Keep `_client_stream` alive until after peer_cred() / verify_peer_uid() assertions.
        // On macOS, getpeereid() (the peer_cred() implementation) returns ENOTCONN if the
        // peer has already closed its end of the socket — so the client must not be dropped
        // before the peer_cred() call completes.
        let _client_stream = connect_result.expect("connect");

        // Verify peer_cred() returns the current process UID.
        let peer_uid = server_stream
            .peer_cred()
            .expect("AC-009: peer_cred() must succeed")
            .uid();

        assert_eq!(
            peer_uid, own_uid,
            "AC-009: self-connection peer UID must equal own UID"
        );

        // Structural verification: if peer_uid != own_uid, verify_peer_uid returns Err.
        // We cannot manufacture a real mismatch without root, but we can verify the
        // function correctly identifies same-uid connections as Ok — confirming the
        // comparison logic is wired correctly and that non-matching UIDs would fall
        // through to the error branch (BC-2.08.003 Invariant 5).
        let ok_result = verify_peer_uid(&server_stream, "test-session-ac009-uid");
        assert!(
            ok_result.is_ok(),
            "AC-009: same-UID peer must be accepted by verify_peer_uid"
        );

        let _ = std::fs::remove_file(&sock_path);
    }

    // -----------------------------------------------------------------------
    // IMP-002: acceptor-side SO_PEERCRED reject branch — pure unit tests for
    // `check_peer_uid`.
    //
    // Adversarial pass-6 finding F-S034-ADV-IMP-002.
    //
    // `check_peer_uid(peer_uid, own_uid)` is pub(crate) and accessible via
    // `super::check_peer_uid` from this test module. These tests exercise BOTH
    // branches of the comparison without requiring root or a different OS user.
    //
    // References: AC-009, BC-2.08.003 Invariant 5 (acceptor side).
    // -----------------------------------------------------------------------

    /// IMP-002 (mismatch → PermissionDenied): check_peer_uid(1000, 0) must return
    /// Err with ErrorKind::PermissionDenied and the expected message format.
    ///
    /// This is the genuine negative test that the misleading
    /// `test_BC_2_08_003_AC009_so_peercred_uid_mismatch_returns_permission_denied`
    /// claimed to cover but did not.  The function is called directly so that
    /// no root privileges or forked process are needed.
    ///
    /// F-S034-ADV-IMP-002 / AC-009 / BC-2.08.003 Invariant 5.
    #[test]
    fn test_BC_2_08_003_IMP002_check_peer_uid_mismatch_returns_permission_denied() {
        let result = super::check_peer_uid(1000, 0);

        // Must be Err — a mismatch must never succeed.
        assert!(
            result.is_err(),
            "IMP-002 (AC-009 / BC-2.08.003 Inv5): check_peer_uid(1000, 0) must return Err; \
             got Ok(())"
        );

        let err = result.unwrap_err();

        // Must be SessionHostError::Io wrapping PermissionDenied.
        match &err {
            SessionHostError::Io(io_err) => {
                assert_eq!(
                    io_err.kind(),
                    std::io::ErrorKind::PermissionDenied,
                    "IMP-002: error kind must be PermissionDenied (CWE-284); got {:?}",
                    io_err.kind()
                );
                // Message format: "SO_PEERCRED uid mismatch: peer=<peer> own=<own>"
                let msg = io_err.to_string();
                assert!(
                    msg.contains("SO_PEERCRED uid mismatch"),
                    "IMP-002: error message must contain 'SO_PEERCRED uid mismatch'; got: {:?}",
                    msg
                );
                assert!(
                    msg.contains("peer=1000"),
                    "IMP-002: error message must include peer uid; got: {:?}",
                    msg
                );
                assert!(
                    msg.contains("own=0"),
                    "IMP-002: error message must include own uid; got: {:?}",
                    msg
                );
                // Full format check: "SO_PEERCRED uid mismatch: peer=1000 own=0"
                assert_eq!(
                    msg, "SO_PEERCRED uid mismatch: peer=1000 own=0",
                    "IMP-002: full error message format must match expected pattern"
                );
            }
            other => panic!(
                "IMP-002: expected SessionHostError::Io(PermissionDenied), got {:?}",
                other
            ),
        }
    }

    /// IMP-002 (same uid zero → Ok): check_peer_uid(0, 0) must return Ok(()).
    ///
    /// Root-to-root is a valid same-uid scenario (e.g., root-owned daemon + root-owned host).
    ///
    /// F-S034-ADV-IMP-002 / AC-009 / BC-2.08.003 Invariant 5.
    #[test]
    fn test_BC_2_08_003_IMP002_check_peer_uid_same_zero_returns_ok() {
        let result = super::check_peer_uid(0, 0);
        assert!(
            result.is_ok(),
            "IMP-002 (AC-009): check_peer_uid(0, 0) must return Ok(()); got {:?}",
            result.err()
        );
    }

    /// IMP-002 (equal nonzero → Ok): check_peer_uid(1000, 1000) must return Ok(()).
    ///
    /// Normal user case: both sides run as the same unprivileged UID.
    ///
    /// F-S034-ADV-IMP-002 / AC-009 / BC-2.08.003 Invariant 5.
    #[test]
    fn test_BC_2_08_003_IMP002_check_peer_uid_equal_nonzero_returns_ok() {
        let result = super::check_peer_uid(1000, 1000);
        assert!(
            result.is_ok(),
            "IMP-002 (AC-009): check_peer_uid(1000, 1000) must return Ok(()); got {:?}",
            result.err()
        );
    }

    /// IMP-002 (symmetric mismatch): check_peer_uid(0, 1000) must also return
    /// Err(PermissionDenied) — the comparison is not directional.
    ///
    /// F-S034-ADV-IMP-002 / AC-009 / BC-2.08.003 Invariant 5.
    #[test]
    fn test_BC_2_08_003_IMP002_check_peer_uid_reverse_mismatch_returns_permission_denied() {
        let result = super::check_peer_uid(0, 1000);
        assert!(
            result.is_err(),
            "IMP-002 (AC-009): check_peer_uid(0, 1000) must return Err; got Ok(())"
        );
        let err = result.unwrap_err();
        match err {
            SessionHostError::Io(io_err) => {
                assert_eq!(
                    io_err.kind(),
                    std::io::ErrorKind::PermissionDenied,
                    "IMP-002: reverse mismatch error kind must be PermissionDenied; got {:?}",
                    io_err.kind()
                );
                let msg = io_err.to_string();
                assert_eq!(
                    msg,
                    "SO_PEERCRED uid mismatch: peer=0 own=1000",
                    "IMP-002: reverse mismatch message format must be 'SO_PEERCRED uid mismatch: peer=0 own=1000'; got {:?}",
                    msg
                );
            }
            other => panic!(
                "IMP-002: expected SessionHostError::Io(PermissionDenied), got {:?}",
                other
            ),
        }
    }

    // -----------------------------------------------------------------------
    // Existing tests
    // -----------------------------------------------------------------------

    /// Verify that MONOCLE_SESSION_ID env var is not read or forwarded by the
    /// session-host binary (BC hook constraint BC-HOOK-030).
    ///
    /// The session_id is passed as a CLI arg (--session-id), never via env.
    /// Hooks must NOT see MONOCLE_SESSION_ID in their environment.
    #[test]
    fn test_BC_HOOK_030_monocle_session_id_env_set_not_read_by_hooks() {
        // Verify the binary does NOT expose MONOCLE_SESSION_ID via env inheritance.
        // This is enforced structurally: step_build_command() uses std::env::vars()
        // for env inheritance, and MONOCLE_SESSION_ID is not set in the daemon's
        // environment (the daemon never sets it). The hook scripts must NOT be able
        // to read this variable.
        //
        // This test asserts that the session_id comes from CliArgs.session_id
        // (parsed from --session-id CLI arg), NOT from any env var.
        let args = CliArgs {
            session_id: "test-session-uuid".to_string(),
            runtime_dir: std::path::PathBuf::from("/tmp"),
            binary: std::path::PathBuf::from("/bin/cat"),
            args: vec![],
            env: std::collections::HashMap::new(),
            cwd: std::path::PathBuf::from("/tmp"),
        };

        // session_id is from args struct, not from env.
        assert_eq!(args.session_id, "test-session-uuid");
        // MONOCLE_SESSION_ID is not in the env map.
        assert!(
            !args.env.contains_key("MONOCLE_SESSION_ID"),
            "BC-HOOK-030: MONOCLE_SESSION_ID must not be in the session env overlay"
        );
    }

    // -----------------------------------------------------------------------
    // BC-2.09.006 PC-6/7 — session-host DaemonToHost::Resize arm
    //
    // Postcondition 6: session-host calls `pty.resize(PtySize { rows, cols, .. })`.
    // Postcondition 7: harness child receives SIGWINCH (via portable-pty on pty.resize()).
    //
    // These tests drive `apply_resize_to_pty_and_parser()` — the pure helper that
    // the implementer will extract and call from the `DaemonToHost::Resize` arm in
    // `step_event_loop`.
    //
    // RED GATE: `apply_resize_to_pty_and_parser()` is `todo!()` — panics on every call.
    // -----------------------------------------------------------------------

    /// test_BC_2_09_006_session_host_resize_arm_calls_parser_set_size
    ///
    /// AC-S042-session-host / BC-2.09.006 PC-6:
    ///   `apply_resize_to_pty_and_parser(pty_master, parser, rows, cols)` must call
    ///   `parser.set_size(rows, cols)`. After the call, `parser.screen().size()` must
    ///   return `(30, 100)` (canonical test vector: 24×80 → 30×100).
    ///
    ///   RED GATE: `apply_resize_to_pty_and_parser()` is `todo!()` — panics.
    #[tokio::test]
    async fn test_BC_2_09_006_session_host_resize_arm_calls_parser_set_size() {
        // Create a real PTY pair so pty_master is a valid MasterPty.
        let pty_system = portable_pty::native_pty_system();
        let pair = pty_system
            .openpty(portable_pty::PtySize {
                rows: 24,
                cols: 80,
                pixel_width: 0,
                pixel_height: 0,
            })
            .expect("BC-2.09.006 PC-6 test setup: openpty must succeed — PTY unavailable in CI?");

        let mut parser = step_init_vt100_parser(24, 80);

        // Verify initial size.
        let initial_size = parser.screen().size();
        assert_eq!(
            initial_size,
            (24, 80),
            "BC-2.09.006 PC-6 pre-condition: parser must start at 24×80"
        );

        // RED GATE: todo!() panics here; after implementation parser is at 30×100.
        super::apply_resize_to_pty_and_parser(pair.master.as_ref(), &mut parser, 30, 100)
            .expect("BC-2.09.006 PC-6: apply_resize_to_pty_and_parser(30, 100) must return Ok(())");

        // Assert parser reflects the new size (canonical test vector: 24×80 → 30×100).
        let new_size = parser.screen().size();
        assert_eq!(
            new_size,
            (30, 100),
            "BC-2.09.006 PC-6: parser.screen().size() must be (30, 100) after resize — \
             got {:?}",
            new_size
        );
    }

    /// test_BC_2_09_006_session_host_resize_arm_pty_master_resize_called
    ///
    /// AC-S042-session-host / BC-2.09.006 PC-6/7:
    ///   `apply_resize_to_pty_and_parser()` calls `pty_master.resize(PtySize { rows: 30,
    ///   cols: 100, .. })`. The PTY master resize is observable: after `pty.resize()`,
    ///   `pty_master.get_size()` returns the new size (rows=30, cols=100).
    ///
    ///   RED GATE: `apply_resize_to_pty_and_parser()` is `todo!()` — panics.
    #[tokio::test]
    async fn test_BC_2_09_006_session_host_resize_arm_pty_master_resize_called() {
        let pty_system = portable_pty::native_pty_system();
        let pair = pty_system
            .openpty(portable_pty::PtySize {
                rows: 24,
                cols: 80,
                pixel_width: 0,
                pixel_height: 0,
            })
            .expect("BC-2.09.006 PC-6/7 test setup: openpty must succeed");

        let mut parser = step_init_vt100_parser(24, 80);

        // RED GATE: todo!() panics here.
        super::apply_resize_to_pty_and_parser(pair.master.as_ref(), &mut parser, 30, 100).expect(
            "BC-2.09.006 PC-6/7: apply_resize_to_pty_and_parser(30, 100) must return Ok(())",
        );

        // Assert PTY master reflects the new size via get_size().
        // This also validates PC-7: portable-pty sends SIGWINCH when pty.resize() is called.
        let pty_size = pair
            .master
            .get_size()
            .expect("BC-2.09.006 PC-7: pty_master.get_size() must return the current size");

        assert_eq!(
            pty_size.rows, 30,
            "BC-2.09.006 PC-6/7: PTY master rows must be 30 after resize — got {}",
            pty_size.rows
        );
        assert_eq!(
            pty_size.cols, 100,
            "BC-2.09.006 PC-6/7: PTY master cols must be 100 after resize — got {}",
            pty_size.cols
        );
    }
}
