//! monocle-session-host — per-session supervisor process (S-033).
//!
//! This binary is spawned by the monocle daemon's `RealSessionHostSpawner` for each
//! new session. It owns the PTY master, vt100 parser, harness child handle, and
//! per-session UDS socket.
//!
//! # Startup sequence (SS-session-manager.md §monocle-session-host binary §startup sequence)
//!
//! 1. Parse CLI args: --session-id, --runtime-dir, --binary, --args, --env, --cwd
//! 2. Call nix::unistd::setsid() to become a process group leader
//! 3. Open PTY pair via portable_pty::openpty(PtySize { rows: 24, cols: 80, ... })
//! 4. Build CommandBuilder from --binary/--args/--env/--cwd with env inheritance
//! 5. Spawn harness child on PTY slave
//! 6. Initialize vt100::Parser with initial size
//! 7. Bind per-session UDS socket at <runtime_dir>/session-<session_id>.sock (mode 0o600)
//! 8. Write session-state.json sidecar at <runtime_dir>/session-<session_id>.json
//! 9. Enter main event loop
//!
//! # Error handling
//! All errors at startup cause process exit with a non-zero code. The daemon's
//! post-spawn monitor handles session-host death by transitioning to Terminated.

#![forbid(unsafe_code)]
#![deny(missing_docs)]

use std::collections::HashMap;
use std::path::PathBuf;

use tokio::io::AsyncWriteExt;

/// CLI arguments parsed from the daemon-supplied command line.
///
/// Passed by `RealSessionHostSpawner::spawn()` per SS-session-manager.md
/// §SessionHostSpawner trait.
#[derive(Debug)]
#[allow(dead_code)]
struct CliArgs {
    /// Session UUID string (pre-generated by daemon IPC handler).
    session_id: String,
    /// Daemon's runtime directory (for sidecar + UDS socket placement).
    runtime_dir: PathBuf,
    /// Absolute path to the harness binary (from SpawnRecipe.binary).
    binary: PathBuf,
    /// Harness CLI arguments (from SpawnRecipe.args), JSON-encoded.
    args: Vec<String>,
    /// Env overlay (from SpawnRecipe.env), JSON-encoded key=value pairs.
    env: HashMap<String, String>,
    /// Working directory for the harness child (from SpawnRecipe.cwd).
    cwd: PathBuf,
}

/// Parse CLI arguments from `std::env::args()`.
///
/// Parses: `--session-id <id> --runtime-dir <path> --binary <path>
///   --args <json> --env <json> --cwd <path>`
fn parse_args() -> Result<CliArgs, String> {
    let mut args = std::env::args().skip(1);
    let mut session_id = None::<String>;
    let mut runtime_dir = None::<PathBuf>;
    let mut binary = None::<PathBuf>;
    let mut args_json = None::<String>;
    let mut env_json = None::<String>;
    let mut cwd = None::<PathBuf>;

    while let Some(flag) = args.next() {
        match flag.as_str() {
            "--session-id" => {
                session_id = Some(args.next().ok_or("--session-id requires a value")?);
            }
            "--runtime-dir" => {
                runtime_dir = Some(PathBuf::from(
                    args.next().ok_or("--runtime-dir requires a value")?,
                ));
            }
            "--binary" => {
                binary = Some(PathBuf::from(
                    args.next().ok_or("--binary requires a value")?,
                ));
            }
            "--args" => {
                args_json = Some(args.next().ok_or("--args requires a value")?);
            }
            "--env" => {
                env_json = Some(args.next().ok_or("--env requires a value")?);
            }
            "--cwd" => {
                cwd = Some(PathBuf::from(args.next().ok_or("--cwd requires a value")?));
            }
            other => {
                return Err(format!("unknown flag: {other}"));
            }
        }
    }

    let session_id = session_id.ok_or("missing --session-id")?;
    let runtime_dir = runtime_dir.ok_or("missing --runtime-dir")?;
    let binary = binary.ok_or("missing --binary")?;
    let cwd = cwd.ok_or("missing --cwd")?;

    let harness_args: Vec<String> = args_json
        .as_deref()
        .map(|j| serde_json::from_str(j).map_err(|e| format!("--args JSON parse error: {e}")))
        .transpose()?
        .unwrap_or_default();

    let env: HashMap<String, String> = env_json
        .as_deref()
        .map(|j| serde_json::from_str(j).map_err(|e| format!("--env JSON parse error: {e}")))
        .transpose()?
        .unwrap_or_default();

    Ok(CliArgs {
        session_id,
        runtime_dir,
        binary,
        args: harness_args,
        env,
        cwd,
    })
}

/// Session-host error types.
#[derive(Debug, thiserror::Error)]
#[allow(dead_code)]
enum SessionHostError {
    /// PTY open failed.
    #[error("PTY open failed: {0}")]
    PtyOpenFailed(String),

    /// Harness child spawn failed.
    #[error("harness child spawn failed: {0}")]
    ChildSpawnFailed(String),

    /// UDS socket bind failed.
    #[error("UDS bind failed: {path}: {reason}")]
    UdsBindFailed {
        /// Path of the UDS socket.
        path: String,
        /// Reason for the bind failure.
        reason: String,
    },

    /// Sidecar write failed.
    #[error("sidecar write failed: {path}: {reason}")]
    SidecarWriteFailed {
        /// Path of the sidecar file.
        path: String,
        /// Reason for the write failure.
        reason: String,
    },

    /// I/O error.
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// Argument parse error.
    #[error("argument error: {0}")]
    ArgError(String),
}

/// Entry point. Parses CLI args, runs the startup sequence, enters the event loop.
#[tokio::main]
async fn main() {
    // Initialize tracing subscriber for structured session-host logs.
    // Errors are not surfaced to the daemon via stderr alone (I3-009 — degraded env
    // is surfaced via HostToDaemon::StateChanged { degraded_env: Some(_) }).
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive(tracing::Level::INFO.into()),
        )
        .with_writer(std::io::stderr)
        .init();

    let args = match parse_args() {
        Ok(a) => a,
        Err(e) => {
            tracing::error!("monocle-session-host arg parse error: {e}");
            std::process::exit(1);
        }
    };

    if let Err(e) = run(args).await {
        tracing::error!("monocle-session-host fatal error: {e}");
        std::process::exit(1);
    }
}

/// Run the session-host startup sequence and event loop.
async fn run(args: CliArgs) -> Result<(), SessionHostError> {
    // Step 2: become a process group leader (immune to SIGHUP from daemon exit).
    step_setsid()?;

    // Step 3: open PTY pair (24×80 initial size).
    let pty_system = portable_pty::native_pty_system();
    let pty_pair = pty_system
        .openpty(portable_pty::PtySize {
            rows: 24,
            cols: 80,
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|e| SessionHostError::PtyOpenFailed(e.to_string()))?;

    // Step 4: build CommandBuilder with env inheritance + recipe overlay.
    let cmd = step_build_command(&args)?;

    // Step 5: spawn harness child on PTY slave.
    let mut child = pty_pair
        .slave
        .spawn_command(cmd)
        .map_err(|e| SessionHostError::ChildSpawnFailed(e.to_string()))?;
    let child_pid = child.process_id().ok_or_else(|| {
        SessionHostError::ChildSpawnFailed("child PID unavailable after spawn".to_string())
    })?;

    // Step 6: initialize vt100 parser (stub — no-op process() is fine for S-033).
    let _parser = step_init_vt100_parser(24, 80);

    // Step 7: bind per-session UDS socket with mode 0o600.
    let listener = step_bind_uds(&args.runtime_dir, &args.session_id).await?;

    // Step 8: write session-state.json sidecar atomically with child_pid.
    step_write_sidecar(&args, child_pid).await?;

    // Step 9: enter main event loop.
    step_event_loop(&args.session_id, listener).await?;

    // Reap child process to avoid zombie.
    let _ = child.wait();

    // Drop master PTY when done.
    drop(pty_pair.master);

    Ok(())
}

/// Step 2: Become a process group leader (immune to SIGHUP from daemon exit).
fn step_setsid() -> Result<(), SessionHostError> {
    nix::unistd::setsid()
        .map(|_| ())
        .map_err(|e| SessionHostError::Io(std::io::Error::other(e.to_string())))
}

/// Step 4: Build CommandBuilder with env inheritance + recipe overlay.
///
/// Env inheritance (I2-006 mandatory): seed CommandBuilder with std::env::vars()
/// first, then overlay SpawnRecipe.env on top. Preserves PATH, HOME, TERM.
fn step_build_command(args: &CliArgs) -> Result<portable_pty::CommandBuilder, SessionHostError> {
    let mut cmd = portable_pty::CommandBuilder::new(&args.binary);

    // Seed with current process environment (inherits PATH, HOME, TERM, etc.).
    for (k, v) in std::env::vars() {
        cmd.env(k, v);
    }

    // Overlay recipe-specific env vars (may override inherited vars).
    for (k, v) in &args.env {
        cmd.env(k, v);
    }

    // Set CLI args.
    cmd.args(args.args.iter());

    // Set working directory.
    cmd.cwd(&args.cwd);

    Ok(cmd)
}

/// Step 6: Initialize vt100 parser with initial PTY dimensions and 1000-line scrollback.
///
/// Scrollback capacity: 1000 lines per SS-session-manager.md §Ruling A.
/// The actual PTY-to-TUI byte relay (PtyBytes streaming) is implemented in S-047;
/// for S-033 the parser is created but not actively used.
fn step_init_vt100_parser(rows: u16, cols: u16) -> vt100::Parser {
    vt100::Parser::new(rows, cols, 1000)
}

/// Step 7: Bind per-session UDS socket at `<runtime_dir>/session-<session_id>.sock`
/// with mode 0o600 (per-session UDS security, SS-session-manager.md §Per-session UDS security).
async fn step_bind_uds(
    runtime_dir: &std::path::Path,
    session_id: &str,
) -> Result<tokio::net::UnixListener, SessionHostError> {
    use std::os::unix::fs::PermissionsExt;

    let sock_path = runtime_dir.join(format!("session-{session_id}.sock"));

    // SEC-005 (CWE-59): unconditional best-effort remove before bind — eliminates the
    // TOCTOU race between exists() check and remove_file() that the prior if-exists pattern
    // had. If the socket does not exist, remove_file returns NotFound which we ignore.
    // If removal fails for a real reason (e.g., permission denied), bind() will surface it.
    let _ = std::fs::remove_file(&sock_path);

    let listener = tokio::net::UnixListener::bind(&sock_path).map_err(|e| {
        SessionHostError::UdsBindFailed {
            path: sock_path.to_string_lossy().into_owned(),
            reason: e.to_string(),
        }
    })?;

    // Set permissions to 0o600 (owner read/write only).
    std::fs::set_permissions(&sock_path, std::fs::Permissions::from_mode(0o600)).map_err(|e| {
        SessionHostError::UdsBindFailed {
            path: sock_path.to_string_lossy().into_owned(),
            reason: format!("failed to set socket permissions: {e}"),
        }
    })?;

    Ok(listener)
}

/// Step 8: Read-modify-write session-state.json sidecar (BLOCKER-002 / Ruling B).
///
/// **Ownership protocol (SS-session-manager.md §Ruling B):**
/// - The DAEMON wrote the initial sidecar with all fields populated and `child_pid: None`.
/// - The SESSION-HOST sets ONLY `child_pid = Some(process_id())` and re-persists atomically.
/// - The session-host MUST NOT overwrite daemon-owned fields: `state`, `project_root`,
///   `cwd`, `harness_id`, `profile_id`, `started_at`, `display_name`, or any other field.
///
/// Implementation:
/// 1. Read the existing `SessionSidecarV3` from disk (written by daemon at spawn).
/// 2. Set `child_pid = Some(child_pid)`.
/// 3. Write back atomically via `tempfile::persist` — no field clobber.
async fn step_write_sidecar(args: &CliArgs, child_pid: u32) -> Result<(), SessionHostError> {
    use std::io::Write as _;

    let sidecar_path = args
        .runtime_dir
        .join(format!("session-{}.json", args.session_id));

    // Step 1: read the daemon-written sidecar from disk.
    let existing_json = std::fs::read_to_string(&sidecar_path).map_err(|e| {
        SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: format!("failed to read daemon-written sidecar: {e}"),
        }
    })?;

    let mut sidecar: monocle_ipc::types::SessionSidecarV3 = serde_json::from_str(&existing_json)
        .map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: format!("failed to deserialize daemon-written sidecar: {e}"),
        })?;

    // Step 2: set ONLY child_pid — do NOT touch any other daemon-owned field.
    sidecar.child_pid = Some(child_pid);

    // Step 3: serialize and persist atomically.
    let sidecar_json =
        serde_json::to_vec_pretty(&sidecar).map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: format!("JSON serialization failed: {e}"),
        })?;

    let dir = sidecar_path
        .parent()
        .ok_or_else(|| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: "sidecar path has no parent directory".to_string(),
        })?;

    let mut tmp = tempfile::Builder::new()
        .prefix(".session-sidecar-host-")
        .suffix(".json.tmp")
        .tempfile_in(dir)
        .map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: e.to_string(),
        })?;

    tmp.write_all(&sidecar_json)
        .map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: e.to_string(),
        })?;

    tmp.persist(&sidecar_path)
        .map_err(|e| SessionHostError::SidecarWriteFailed {
            path: sidecar_path.to_string_lossy().into_owned(),
            reason: e.error.to_string(),
        })?;

    tracing::debug!(
        session_id = %args.session_id,
        child_pid = child_pid,
        "session-host: sidecar updated with child_pid (Ruling B read-modify-write)"
    );

    Ok(())
}

/// Send a single `HostToDaemon` message as a length-prefixed JSON frame.
///
/// Frame format: 4-byte LE u32 length + JSON body (per SS-session-manager.md §Per-session UDS protocol).
async fn send_host_msg(
    stream: &mut tokio::net::UnixStream,
    msg: &monocle_ipc::types::HostToDaemon,
) -> Result<(), SessionHostError> {
    let body = serde_json::to_vec(msg)
        .map_err(|e| SessionHostError::Io(std::io::Error::other(e.to_string())))?;
    let len = body.len() as u32;
    stream.write_all(&len.to_le_bytes()).await?;
    stream.write_all(&body).await?;
    stream.flush().await?;
    Ok(())
}

/// Step 9: Main event loop.
///
/// Accepts the daemon's control connection.
///
/// **HIGH-001 (I3-009) startup handshake:**
/// 1. Check `HOME` and `PATH` in the current process environment.
/// 2. If any are missing: send `StateChanged { new_state: Launching, degraded_env: Some([...]) }`
///    as the FIRST message (before `Running`). The daemon sets `entry.degraded = true`.
/// 3. Send `StateChanged { new_state: Running, degraded_env: None }` to signal readiness.
///
/// Deferred handlers (Attach/Resize/KeyInput/Detach) return gracefully for S-033;
/// they will be implemented in S-034/S-035/S-047.
async fn step_event_loop(
    session_id: &str,
    listener: tokio::net::UnixListener,
) -> Result<(), SessionHostError> {
    // Accept the daemon control connection (single accept — post-spawn monitor).
    let (mut stream, _addr) =
        listener
            .accept()
            .await
            .map_err(|e| SessionHostError::UdsBindFailed {
                path: format!("session-{session_id}.sock"),
                reason: format!("accept failed: {e}"),
            })?;

    tracing::debug!(session_id = %session_id, "session-host: daemon connected to control socket");

    // HIGH-001 (I3-009): check critical env vars; send degraded handshake if missing.
    let critical_vars = ["HOME", "PATH"];
    let missing_vars: Vec<String> = critical_vars
        .iter()
        .filter(|&&var| std::env::var(var).is_err())
        .map(|&var| var.to_string())
        .collect();

    if !missing_vars.is_empty() {
        tracing::warn!(
            session_id = %session_id,
            missing = ?missing_vars,
            "session-host: degraded environment detected — sending Launching+degraded handshake (I3-009)"
        );
        let degraded_msg = monocle_ipc::types::HostToDaemon::StateChanged {
            new_state: monocle_ipc::types::SessionState::Launching,
            degraded_env: Some(missing_vars),
        };
        send_host_msg(&mut stream, &degraded_msg).await?;
    }

    // Send HostToDaemon::StateChanged{Running} as length-prefixed JSON.
    // degraded_env is always None on the Running message (metadata was in the Launching message).
    let msg = monocle_ipc::types::HostToDaemon::StateChanged {
        new_state: monocle_ipc::types::SessionState::Running,
        degraded_env: None,
    };

    send_host_msg(&mut stream, &msg).await?;

    tracing::info!(session_id = %session_id, "session-host: sent StateChanged{{Running}} to daemon");

    // Minimal shutdown wait: drain one message or wait for daemon to close.
    // S-034/S-035/S-047 implement full Kill/Attach/Resize/Detach handling.
    use tokio::io::AsyncReadExt;
    let mut len_buf = [0u8; 4];
    match stream.read_exact(&mut len_buf).await {
        Ok(_) => {
            let msg_len = u32::from_le_bytes(len_buf) as usize;
            if msg_len <= 1024 * 1024 {
                let mut body = vec![0u8; msg_len];
                if stream.read_exact(&mut body).await.is_ok() {
                    tracing::debug!(session_id = %session_id, "session-host: received DaemonToHost message, exiting");
                }
            } else {
                tracing::warn!(session_id = %session_id, "session-host: oversized message, closing");
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => {
            tracing::debug!(session_id = %session_id, "session-host: daemon closed control connection");
        }
        Err(e) => {
            tracing::warn!(session_id = %session_id, error = %e, "session-host: control connection error");
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(non_snake_case)]
mod tests {
    use super::*;

    /// Verify that MONOCLE_SESSION_ID env var is not read or forwarded by the
    /// session-host binary (BC hook constraint BC-HOOK-030).
    ///
    /// The session_id is passed as a CLI arg (--session-id), never via env.
    /// Hooks must NOT see MONOCLE_SESSION_ID in their environment.
    #[test]
    fn test_BC_HOOK_030_monocle_session_id_env_set_not_read_by_hooks() {
        // Verify the binary does NOT expose MONOCLE_SESSION_ID via env inheritance.
        // This is enforced structurally: step_build_command() uses std::env::vars()
        // for env inheritance, and MONOCLE_SESSION_ID is not set in the daemon's
        // environment (the daemon never sets it). The hook scripts must NOT be able
        // to read this variable.
        //
        // This test asserts that the session_id comes from CliArgs.session_id
        // (parsed from --session-id CLI arg), NOT from any env var.
        let args = CliArgs {
            session_id: "test-session-uuid".to_string(),
            runtime_dir: std::path::PathBuf::from("/tmp"),
            binary: std::path::PathBuf::from("/bin/cat"),
            args: vec![],
            env: std::collections::HashMap::new(),
            cwd: std::path::PathBuf::from("/tmp"),
        };

        // session_id is from args struct, not from env.
        assert_eq!(args.session_id, "test-session-uuid");
        // MONOCLE_SESSION_ID is not in the env map.
        assert!(
            !args.env.contains_key("MONOCLE_SESSION_ID"),
            "BC-HOOK-030: MONOCLE_SESSION_ID must not be in the session env overlay"
        );
    }
}
